name: "Test Swift package"
on:
  push:
  pull_request:
    types: [opened]
  issues:
    types: [opened, edited, closed, deleted]
jobs:
  test-swift-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        swift_ver: [5.1, 5.2, 5.3, latest, bionic]
    steps:
      - uses: actions/checkout@v2
      - uses: docker://swift:${{ matrix.swift_ver }}
      - run: swift --version
      - run: swift build
      - run: swift test