name: "Test Swift package"
on:
  push:
  pull_request:
    types: [opened]
  issues:
    types: [opened, edited, closed, deleted]
jobs:
  test-swift-5-3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: docker://swift:5.3
      - run: swift test --parallel

  test-swift-latest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: docker://swift:latest
      - run: swift test --parallel