name: test-swift-package.yml
on: [push]
jobs:
  test-swift-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://swift:5.3
      - run: swift --version
      - run: swift build
      - run: swift test