name: "Test Swift package"
on:
  push:
  pull_request:
    types: [opened]
  issues:
    types: [opened, edited, closed, deleted]
jobs:
  test-swift-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]
        swift_ver: [5.3, 5.2]
    steps:
      - uses: actions/checkout@v2
      - uses: docker://swift:$SWIFT_VER
        env:
          SWIFT_VER: ${{ matrix.swift_ver }}
      - name: Swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Test
        run: swift test